### ISSUE TITLE
InfografíaHilos-DiegoAlexisCarlosCruz

### ISSUE THREAD

**Issue by Diego047** [SistemasTecTlaxiaco/infografia-de-hilos-Diego047#2]
[HILOS-DiegoAlexisCarlosCruz.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-Diego047/files/8385986/HILOS-DiegoAlexisCarlosCruz.pdf)

**Comment by Gregorio012** [comment]
Calificación 19

**Comment by josealfredo79** [comment]
Esta practica no es 
![image](https://user-images.githubusercontent.com/58342642/170903965-9a55d939-cbf1-443d-9387-f43628a79dce.png)

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
